README.md
Update quick start section in readme
=> fix(docs): update installation instruction

README.md
Signed-off-by: somesh kumar <somesh.kumar@mayadata.io>
1. updated README.md to install jiva-operator
=> refactor(readme): Update readme to install jiva-operator

deploy/operator.yaml, pkg/controller/jivavolume/jivavolume_controller.go
=> refact(replica): pass pv size of replicas in user readable format

pkg/jiva/client.go, pkg/volume/stats.go
This commit adds resize schema and add SetTimeout method for REST API call to jiva volume controller.
=> feat(jiva): add resize schema for REST API call

.travis.yml, Makefile, build/push
=>  fix(make): add push script to push container images

CHANGELOG.md
=> doc(changelog): add changelog for 1.7.0-RC1

Makefile, build/push
=> fix(ci): fix credentials for quay

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, GOVERNANCE.md, MAINTAINERS, RELEASE.md, code-standard.md, developer-setup.md
=> docs(project): add project specific docs

.travis.yml
Remove the hardcoding of openebs in the downstream
release tagging.
Signed-off-by: kmova <kiran.mova@mayadata.io>
=> refactor(build):enable downstream tagging on custom repo

.travis.yml, build/git-release
=> refact(build): ignore error if tag already exists

.travis.yml, build/git-release
(cherry picked from commit 26ac6d4d10576d616c3f324f7cb3f22dd1514f51)
=> refact(build): ignore error if tag already exists (#19)

Makefile, deploy/crds/openebs.io_jivavolumepolicies_crd.yaml, deploy/crds/openebs.io_jivavolumes_crd.yaml, deploy/operator.yaml, pkg/apis/openebs/v1alpha1/jivavolume_types.go, pkg/apis/openebs/v1alpha1/jivavolumepolicy_types.go
This PR 
- adds json tags
- adds proper kubebuilder comments
- removes status subresource
=> fix(crds): update the crds with proper json tags

.github/workflows/chart-lint-test.yml, .github/workflows/release-charts.yml, ct.yaml
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
=> feat(charts): set up helm chart ci and release workflow

.github/workflows/pull_request.yml, ci/ci.sh, deploy/jiva-csi.yaml, go.mod, pkg/controller/jivavolume/jivavolume_controller.go, pkg/driver/controller.go, pkg/driver/grpc.go, pkg/driver/mount.go, pkg/driver/node.go, pkg/driver/stats.go, pkg/driver/utils.go, pkg/jivavolume/jivavolume.go, pkg/kubernetes/client/client.go, tests/provision_test.go, tests/pvc_without_app_test.go, tests/remount_test.go, tests/resize_test.go, tests/utils.go, tests/yamls.go
=> feat(raw-block-volumes): add support for raw block volumes

go.mod, pkg/controller/jivavolume/jivavolume_controller.go
=> refact(logs): Use logrus for logging

README.md, _config.yaml, index.md
=> feat(charts): setup gh-pages content for jiva helm charts hosting

CHANGELOG.md, changelogs/released/v2.6.0/28-shubham14bajpai, changelogs/released/v2.6.0/30-shubham14bajai, changelogs/released/v2.6.0/31-prateekpandey14, changelogs/released/v2.6.0/32-shubham14bajpai, changelogs/released/v2.6.0/33-payes, changelogs/released/v2.6.0/34-shubham14bajpai, changelogs/released/v2.6.0/35-prateekpandey14, changelogs/released/v2.6.0/37-prateekpandey14, changelogs/released/v2.6.0/39-prateekpandey14, changelogs/released/v2.6.0/40-shubham14bajpai, changelogs/released/v2.6.0/41-payes
=> chore(CHANGELOG): add changelogs for v2.6.0

ci/ci.sh, deploy/jiva-csi.yaml, deploy/operator.yaml, pkg/controllers/jivavolume_controller.go
=> fix(operator): add serviceAccountName to replica sts

Makefile, README.md, RELEASE.md, build/push
Since Travis no longer part of build and CI
renaming the build ENV and tags vars information
=> chore(build): update build tag and env names

deploy/crds/openebs.io_jivavolumes.yaml, deploy/operator.yaml, pkg/apis/openebs/v1alpha1/jivavolume_types.go, pkg/controllers/jivavolume_controller.go
=> feat(operator): add ability to scale up replicas via CR

cmd/manager/main.go, pkg/controllers/jivavolume_controller.go
This PR adds to the jiva volume controller. This will enable a single point of debugging and help users get usuable information without going through long log files. This PR also improves the logging for env and errors.
Example events:
```
Events:
Type     Reason          Age                  From                   Message
----     ------          ----                 ----                   -------
Warning  Bootstrap       34m (x25 over 35m)   jivavolume-controller  failed to bootstrap volume, due to error: failed to get volume policy example-jivavolumepolicy: JivaVolumePolicy.openebs.io "example-jivavolumepolicy" not found
Warning  ReplicaScaleup  2s (x6 over 12s)     jivavolume-controller  failed to scaleup volume, only single replica …
```
=> feat(operator): add events to the jivavolume controller

.github/workflows/build.yaml
Add missing docker login and export tag env in build stage of github action.
=> fix(build): add missing docker login and set tag stages

.github/workflows/build.yaml, .github/workflows/pull_request.yml, .github/workflows/release.yaml, cmd/manager/main.go, pkg/controllers/jivavolume_controller.go, pkg/driver/controller.go
This PR cherry-picks the following PRs
- #60 
- #58 
- #57 
- #56
=> chore(v2.7.x): cherry-pick the PRs from master branch

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/crds/jivavolumepolicy.yaml, deploy/helm/charts/crds/jivavolumes.yaml, deploy/helm/charts/templates/jiva-operator.yaml, deploy/helm/charts/values.yaml
- update chart version
- update dependent chart version
- update README
- update values.yaml
- update jiva-operator args
- update crds
=> [stable/jiva]: update charts to 2.7.0 release

README.md, docs/prerequisites/rancher_prerequisite.md, docs/quickstart.md, docs/tutorials/block_volume.md, docs/tutorials/policies.md, docs/tutorials/resize.md
This PR updates README with the following info:
1. Jiva Volume Provisioning steps
2. Jiva policies tutorial
3. Links to slack and openebs repos
4. Compatibility and feature matrix
=> feat(docs): update readme with latest changes

CHANGELOG.md, changelogs/released/v2.8.0/64-shubham14bajpai, changelogs/released/v2.8.0/65-shubham14bajpai
=> chore(docs): add v2.8.0 released changelogs

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
- update chart version
- update localpv dependency version 2.8.0
- update README
- update values.yaml
=> [stable/jiva]: update jiva charts to 2.8.0

CONTRIBUTING.md, README.md
=> chore(docs): update project status and refactor docs

pkg/driver/driver.go, pkg/driver/node.go
=> Unused code removal

tests/suite_test.go
=> Remove dead unused code

tests/suite_test.go
Unused openebs function removal
=> Unused openebs function removal

tests/utils.go
=> Remove unused functions

pkg/kubernetes/pvc/persistentvolumeclaim.go, pkg/kubernetes/volume/volume.go, tests/suite_test.go
Cleaning up unused functions and imported files
=> Cleaning up unused functions and imported files

pkg/driver/mount.go
=> (style) : fixes Potential file inclusion via variable

pkg/kubernetes/client/client.go, pkg/kubernetes/pvc/persistentvolumeclaim_test.go, tests/utils.go
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
- bugsbash related
- Note : It is not a duplicate of https://github.com/openebs/jiva-operator/pull/74/files
=> (refactor) remove deadcode

pkg/driver/mount.go
=> (style) : fix deferring unsafe method Close on type *os.File

pkg/driver/grpc.go, pkg/driver/mount.go, pkg/usage/versionset.go
=> (refactor): handle errors

pkg/driver/node.go
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
Related to bugsbash
=> (refactor) : remove some more deadcode

deploy/helm/charts/Chart.yaml, deploy/helm/charts/templates/jiva-operator.yaml, deploy/operator.yaml, pkg/controllers/jivavolume_controller.go
This PR replaces the hardcoded serviceAccountName for the volume controller and replica workloads.
=> fix(operator): use configurable serviceAccount

pkg/kubernetes/client/client.go
=> fix(csi): create jivaVolume CR in the csi controller namespace

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/crds/upgradetask.yaml, deploy/helm/charts/values.yaml
=> [stable/jiva]: update jiva charts to 2.9.0 release

CHANGELOG.md, changelogs/released/v2.10.0-RC1/95-shubham14bajpai, changelogs/released/v2.10.0-RC1/97-shubham14bajpai, changelogs/released/v2.9.0-RC2/88-shubham14bajpai
This PR adds changelog for v2.10.0 and v2.9.0 releases
=> chore(docs): add v2.9.0 v2.10.0 released changelogs

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
- Update README
- values.yaml
- Update Chart.yaml
=> [stable/jiva]: update helm chart to 2.10.0 release

pkg/controllers/jivavolume_controller.go
This PR addresses the issue where the volume replica STS keeps crashing due to change in the cluster domain. Earlier the domain name was hard coded as cluster.local and the changes replaces that domain name with the service IP of the controller service. Ref: #99
=> fix(operator): replace svc dns name to clusterIP in replica STS

pkg/controllers/jivavolume_controller.go, pkg/kubernetes/client/client.go
This PR cherry-picks the PRs:
- #101 
- #102
=> chore(cherry-pick): fix replica sts for custom domains and analytics 

pkg/driver/node.go
This PR addresses the issue https://github.com/openebs/openebs/issues/3404 where more than 1 pod was able to mount a RWO volume and resulted in I/O Errors. The changes add checks to prevent mounting on another node by
- checking if the jivaVolume `spec.mountInfo`  is already populated by another mount
- also if the previously mounted node is ready or not, if not mounting to another node is allowed
Test scenarios covered manually on a EKS cluster:
- deploying 2 replica deployment pods on different nodes for a RWO volume, 1 replica failed to mount the volume
- deploying another pod on a different node when a pod already has the RWO volume mounted, the second pod failed to mount the volume
- node on which the pod was running moved out of …
=> fix(csi): prevent volume mount on multiple nodes simultaneously

.github/workflows/build.yaml, .github/workflows/pull_request.yml, version/util.go
This PR Adds 2.11.0 to the upgrade matrix.
=> chore(version): add 2.11.0 to upgrade matrix

.github/workflows/chart-lint-test.yml, deploy/helm/charts/Chart.yaml
Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
Update localpv chart version to v2.10.1
=> chore(charts): Update localpv chart version

.github/workflows/build.yaml, .github/workflows/pull_request.yml, cmd/manager/main.go, deploy/hostpath-sc.yaml, pkg/controllers/jivavolume_controller.go
=> fix(status): fetch volume status using controller podIP 

CHANGELOG.md, changelogs/released/v2.11.0-RC1/107-shubham14bajpai, changelogs/released/v2.11.0-RC1/112-shubham14bajpai
This PR updates the v2.11.0 changelogs
=> chore(docs): add v2.11.0 released changelog

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
Updated Chart.yaml values.yaml and README with 2.11.0 release
=> [stable/jiva]: update jiva charts to 2.11.0 release

deploy/helm/charts/Chart.yaml
Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
Ref: https://github.com/openebs/dynamic-localpv-provisioner/issues/71
Depends on https://github.com/openebs/dynamic-localpv-provisioner/pull/72
=> chore(charts): Update openebs-localpv/localpv-provisioner chart version to 2.11.1

Adopters.md, README.md
=> refact(docs): update Project README and adopters docs

e2e-tests/experiments/jiva-operator/jiva-csi-provisioner/test.yml, e2e-tests/experiments/jiva-operator/jiva-csi-provisioner/test_vars.yml, e2e-tests/experiments/jiva-operator/jiva-csi-storage-policies/localpv-sc.yml, e2e-tests/experiments/jiva-operator/jiva-csi-storage-policies/test.yml, e2e-tests/experiments/jiva-operator/jiva-csi-storage-policies/test_vars.yml
- This test case is to include the provisioning of hostpath-localpv operator yaml as this localpv-provisioner is the prerequisite for provisioning the jiva csi volumes
=> refactor[e2e]: Modify the test case to provision the jiva operator

e2e-tests/experiments/jiva-operator/jiva-csi-provisioner/test.yml, e2e-tests/experiments/jiva-operator/jiva-csi-provisioner/test_vars.yml
=> refactor(e2e): Updated the e2e test case for provisioning jiva operator

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/templates/default-storageclass.yaml, deploy/helm/charts/values.yaml
=> [stable/jiva]: update jiva charts to 2.12.0 release

.gitignore, deploy/crds/openebs.io_jivavolumepolicies.yaml, deploy/crds/openebs.io_jivavolumes.yaml, deploy/crds/openebs.io_v1alpha1_jivavolumepolicy_cr.yaml, deploy/operator.yaml, docs/quickstart.md, pkg/apis/openebs/v1alpha1/jivavolumepolicy_types.go, pkg/controllers/jivavolume_controller.go, pkg/kubernetes/client/client.go, tests/yamls.go
- Updated JivaVolumePolicy fields:
-  monitor --> disableMonitor
-  enableBufio and autoScaling removed 
- Update port name for the exporter in service from m-exporter to exporter.
- Fixes #128
=> fix(operator) Update JivaVolumePolicy parameter(monitor, enableBufio and autoScaling) 

e2e-tests/experiments/jiva-operator/jiva-csi-provisioner/test_vars.yml
- This PR updates the changes made in the openebs/charts repo as part of this PR `https://github.com/openebs/charts/pull/255`
=> refactor[e2e]: Updated the path for the jiva operator yaml

e2e-tests/experiments/jiva-operator/jiva-csi-provisioner/test_vars.yml
- This PR updates the changes made in the openebs/charts repo as part of this PR `https://github.com/openebs/charts/pull/255`
=> refactor[e2e]: Updated the path to fetch RC tag yaml

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
Please, go through these steps before you submit a PR.
- update sidecars version
- update Jiva release 2.12.2
=> [stable/jiva]: bump csi sidecars and jiva version to 1.12.2

docs/tutorials/policies.md
fixes:#124 
Refer PR #132 for more details
=> chore(docs): add replica STS pod anti affinity policies docs

.github/pull_request_template.md, .github/workflows/build.yaml, .github/workflows/chart-lint-test.yml, .github/workflows/pull_request.yml, .github/workflows/release-charts.yml, .github/workflows/release.yaml, ADOPTERS.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, GOVERNANCE.md, Makefile, README.md, RELEASE.md, build/git-release, build/push, code-standard.md, developer-setup.md, docs/quickstart.md, e2e-tests/experiments/jiva-operator/jiva-csi-provisioner/run_e2e_test.yml, e2e-tests/experiments/jiva-operator/jiva-csi-provisioner/test.yml, e2e-tests/experiments/jiva-operator/jiva-csi-provisioner/test_vars.yml, hack/update-codegen.sh, version/util.go
Signed-off-by: kmova <kiran.mova@mayadata.io>
**Why is this PR required? What issue does it fix?**:
As per inclusive naming convention - changing master to develop. 
**What this PR does?**:
Update various references from `master` to `develop`.
Also updated:
- Different guides with latest process changes
- Added GHCR as a target registry
**Does this PR require any upgrade changes?**:
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:
No
**Any additional information for your reviewer?** : 
_Mention if this PR is part of any design or a continuation of previous PRs_
Helm chart-related references need to be updated. Will take them after the workflows have been updated. 
**Checklist:**
=> refactor(repo): rename from master to develop

deploy/jiva-csi.yaml
**What this PR does?**:
This PR adds custom priority classes to the csi yaml for clusters like gcp where the standard node and cluster classes don't work. 
Verified helm is already using the custom classes.
**Does this PR require any upgrade changes?**:
**If the changes in this PR are manually verified, list down the scenarios covered:**:
**Any additional information for your reviewer?** : 
_Mention if this PR is part of any design or a continuation of previous PRs_
**Checklist:**
=> fix(deploy): update csi yaml with custom priorityclasses

docs/tutorials/policies.md
Cherry pick. https://github.com/openebs/jiva-operator/commit/dbe4946f63b6e18b2ac49a68727fbe31fc752daf
=> chore(docs): add replica STS pod anti affinity policies
