openebs/jiva-operator

pkg/apis/openebs/v1alpha1/jivavolume_types.go

This commit adds target path info in jivavolume CR, targetPath is provided by
K8s in NodePublishVolume rpc call. This info will be helpful in remounting
the volume.

refact(jivavolume): add targetpath

---

.travis.yml
build/git-release

Jiva Control Plane code is split across multiple repos.
For releasing jiva control plane code, multiple repo's need
to be tagged in a certain order.
This fix will help to trigger the release
on the downstream repo. In this case, after
releasing openebs/jiva-operator, the following repos should be
tagged:
- openebs/jiva-csi
Note: Due to multiple jobs running in travis,
the release on the downstream should be done
only after the longest job that pushes the
containers is completed. This is manually
configured via ENV variable RELEASE_DOWNSTREAM.
Signed-off-by: kmova <kiran.mova@mayadata.io>

chore(build): trigger downstream repo release

---

.travis.yml

**Why is this PR required? What issue does it fix?**:
Earlier We were tagging release with semantic version 1.x.x, which is changed to v1.x.x and there are cases where tag can be on custom release branches, like v1.9.x-hotfix or v1.9.x-custom, apart from regular release branch (v1.9.x).
**What this PR does?**:
This PR fixes the tagging for downstream repo with new semver(like v1.9.1) and also translate the given tag to the corresponding release branch with custom suffixes.
Using the new logic, some examples of tag to branch mappings are:
v1.9.0-RC1 => v1.9.x
v1.9.0-hotfixid => v1.9.x-hotfixid
v1.9.0 => v1.9.x
v1.9.1 => v1.9.x
v1.9.0-custom-RC1 => v1.9.x-custom
v1.9.0-custom => v1.9.x-custom
v1.9.1-custom => v1.9.x-custom
**Does this PR require any upgrade changes?**:
NA
**If the changes …

refactor(travis): fixing travis for tagging downstream repo

---

pkg/apis/openebs/v1alpha1/jivavolumepolicy_types.go
pkg/controller/jivavolume/jivavolume_controller.go
pkg/kubernetes/podtemplatespec/podtemplatespec.go

This PR adds implementation for tuneable of controller and replica pods:
- monitor
- auxResources
- tolerations 
- serviceAccountName
- priorityClassName
- NodeSelector

feat(policy): add support for target and replica tuneables 

---

pkg/controller/jivavolume/jivavolume_controller.go

This PR adds support for target affinity via policy where the controller pod and be scheduled according to the target affinity mentioned in the policy. For the replica, it has anti-affinity by default and affinity can be achieved via localpv storageclass https://docs.openebs.io/docs/next/uglocalpv-hostpath.html#create-storageclass

feat(policy): add support for target affinity for controller

---

deploy/operator.yaml
pkg/controller/jivavolume/jivavolume_controller.go

This PR removes the defer call and adds a break statement to enable reconcile on failed volumes.
It also adds the rbac which were removed accidentally in a previous PR #34

fix(reconcile): removed defer to enable reconcile on failed volumes

---

pkg/driver/node.go
pkg/kubernetes/client/client.go

**What this PR does**:
Now user can label the nodes with the required custom topology, the jiva-csi  driver will support all the node labels as topology keys.
Ideally we should label the nodes first and then deploy the driver to make it aware of all the labels that node has been configured. 
If we want to add labels on the Nodes after Jiva CSI driver has been deployed, a restart all the csi-node daemonset pods are required so that the driver can pick the labels and add them as supported topology keys.
**How the changes has been tested :**
1. Label all the similar nodes using the same key value and use that label to create the StorageClass
```sh
$ kubectl label node node-1 node-2 openebs.io/nodegroup=storage
```
2. Now, restart …

feat(topology): add custom topology key support for provisioning

---

.github/workflows/chart-lint-test.yml
.github/workflows/pull_request.yml
deploy/helm/charts/.helmignore
deploy/helm/charts/Chart.yaml
deploy/helm/charts/README.md
deploy/helm/charts/crds/jivavolumepolicy.yaml
deploy/helm/charts/crds/jivavolumes.yaml
deploy/helm/charts/templates/NOTES.txt
deploy/helm/charts/templates/_helpers.tpl
deploy/helm/charts/templates/csi-controller-rbac.yaml
deploy/helm/charts/templates/csi-controller.yaml
deploy/helm/charts/templates/csi-driver.yaml
deploy/helm/charts/templates/csi-iscsiadm-config.yaml
deploy/helm/charts/templates/csi-node-rbac.yaml
deploy/helm/charts/templates/csi-node.yaml
deploy/helm/charts/templates/jiva-operator-rbac.yaml
deploy/helm/charts/templates/jiva-operator.yaml
deploy/helm/charts/templates/priority-class.yaml
deploy/helm/charts/templates/psp.yaml
deploy/helm/charts/templates/snapshot-class.yaml
deploy/helm/charts/values.yaml
deploy/jiva-csi.yaml

Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
$ helm install openebs --dry-run --namespace openebs . --set openebsLocalpv.enabled=false 
```
NAME: openebs
LAST DEPLOYED: Wed Feb 10 22:01:34 2021
NAMESPACE: openebs
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
kind: ServiceAccount
apiVersion: v1
metadata:
name: openebs-jiva-csi-controller-sa
labels:
chart: jiva-2.6.0
heritage: Helm
openebs.io/version: "2.6.0"
name: "openebs-jiva-csi-controller"
release: openebs
component: "openebs-jiva-csi-controller"
openebs.io/component-name: "openebs-jiva-csi-controller"
namespace: openebs
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: openebs-jiva-csi-node-sa
labels:
chart: jiva-2.6.0
heritage: Helm
openebs.io/version: "2.6.0"
name: …
```

feat(charts): add helm charts for jiva operator

---

deploy/operator.yaml

This PR contains changes required in openshift based cluster which needs these permission to
be enabled for jiva-operator role to set the ownerreference in stateful set pods.
Note: Required in OpenShift based k8s clusters
**Error:**
```sh
Warning  FailedCreate  4m6s (x12 over 4m16s)   statefulset-controller  create Pod pvc-716d9b78-02e3-4964-a529-b37ef69e13db-jiva-rep-0 in StatefulSet pvc-716d9b78-02e3-4964-a529-b37ef69e13db-jiva-rep failed error: failed to create PVC openebs-pvc-716d9b78-02e3-4964-a529-b37ef69e13db-jiva-rep-0: persistentvolumeclaims "openebs-pvc-716d9b78-02e3-4964-a529-b37ef69e13db-jiva-rep-0" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
Warning  FailedCreate  3m56s (x13 over 4m16s) …
```

fix(operator): update role to use statefulset ownerreference permission

---

deploy/crds/openebs.io_jivavolumes.yaml
deploy/operator.yaml
pkg/apis/openebs/v1alpha1/jivavolume_types.go
pkg/controllers/jivavolume_controller.go

This PR adds the following:
- a spec field named desiredReplicationFactor which will be used to scale up replicas automatically
- controller implementation for the above
- updates the CRDs for the above change

feat(operator): add ability to scale up replicas via CR

---

.github/workflows/pull_request.yml
pkg/driver/controller.go

If resize is attempted even if the previous resize was successful, jiva throws the following error:
```
Volume size same as size mentioned
```
This PR catches this error and returns success to kubernetes if the volume is already resized.

fix(resize): respond success if volume is already of same size

---

.github/workflows/build.yaml
.github/workflows/release.yaml

This PR removes the cache env from the ci builds which was preventing the images from being pushed. It also removes the push command failing due to the push script as the docker buildx automatically pushes the images on release workflow.

fix(build): remove cache env from ci builds

---

pkg/controllers/jivavolume_controller.go

This PR fixes the jiva volume controller, the node selector for the replica sts was checking for the Target instead of the Replica spec in the policy of the jiva volume CR.

fix(controller): fix node selector for replica sts

---

deploy/helm/charts/Chart.yaml
deploy/jiva-csi.yaml
version/util.go

With k8s v1.22 the v1beta1 for various resources will no longer be supported. This PR updates the csi driver api version to v1.
This PR also bumps the version matrix for v2.8.0

chore(k8s): updated csi driver version to v1

---

.github/workflows/build.yaml
.github/workflows/pull_request.yml
.github/workflows/release.yaml
version/util.go

Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
The build.yml and pull_request.yml workflows will ignore pushes made to `deploy/helm/`, `changelogs/` and 'docs/' directories. all .md files, LICENSE and MAINTAINERS files.
Added criteria to ignore build workflows on release.
Build & Push is performed using Actions and not the makefile directly.

chore(github-action): Refine GitHub Actions criteria for builds, pull requests and release, added Build & Push

---

deploy/helm/charts/Chart.yaml
deploy/helm/charts/templates/_helpers.tpl
deploy/helm/charts/templates/csi-controller.yaml
deploy/helm/charts/templates/csi-node.yaml
deploy/helm/charts/templates/priority-class.yaml
deploy/helm/charts/values.yaml

Include storage engine name in priority class name to make sure CSI driver of different storage will have different priority class. This will resolve the issue of installing multiple storage engine using helm chart.
What will happen to older priority classes(upgrade scenario)?
=> Older priority classes will be deleted and CSI node and controller driver pod will be restarted with new priority classes.

fix(helm chart): rename priority class name for CSI plugin (node and controller)

---

deploy/helm/charts/Chart.yaml
deploy/helm/charts/README.md
deploy/helm/charts/values.yaml

Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
This PR does:
1. Disables installation of NDM components by adding default `localpv-provisioner` options to values.yaml
2. Disables installation of openebs-device StorageClass by adding default `localpv-provisioner` options to values.yaml
3. Bumps dependency chart version to 2.8.1
4. Bumps release chart version to 2.8.3. This is to test the release-chart action, as 2.8.2 release failed to create the chart .tgz resource

chore(helm-chart): Disable NDM installation by default, test release with 2.8.3

---

pkg/kubernetes/client/client.go

This PR addresses the issue : #92 
Earlier jiva was designed to run the volume pods in the application namespace, but we decided to have all openebs related pods in one namespace itself. The jiva-csi controller still was expecting the namespace param from the policy and setting the namespace as default `openebs`. All the envs are already set up correctly on the helm and operator charts.

fix(csi): create jivaVolume CR in the csi controller namespace

---

deploy/helm/charts/Chart.yaml
deploy/helm/charts/README.md
deploy/helm/charts/templates/default-policy.yaml
deploy/helm/charts/templates/default-storageclass.yaml
deploy/helm/charts/values.yaml
deploy/jiva-csi.yaml

This PR adds a default jiva volume policy and a default storageclass while deploying using helm charts

feat(charts): add default policy and storageclass

---

deploy/helm/charts/Chart.yaml
deploy/helm/charts/templates/jiva-operator-rbac.yaml
deploy/operator.yaml
docs/quickstart.md
pkg/controllers/jivavolume_controller.go
version/util.go

When a node is removed from the cluster which had a replica pod scheduled on it, then the pod remains stuck in pending state as the openebs localpv volume has node affinity for the missing node. This PR adds the automation to [clean up](https://github.com/kmova/dynamic-localpv-provisioner/blob/example-custom-affinity/docs/feature-custom-affinity.md#ephemeral-storage) the stale volume and restart the pending pod so that it moves to some new node.
Fixes: #96 
Successfully tested the scenario on AWS cluster.

feat(operator): automate movement replicas when node is removed from cluster

---

pkg/kubernetes/client/client.go

There was a issue that, we were returning from the createvolume method before sending the *provisioning analytics* event in case of successful volume creation.
**How the changes has been verified**
Provisioned and deprovisioned the volume and verified the events

fix(analytics): send provisioning event before return

---

deploy/helm/charts/Chart.yaml
deploy/helm/charts/README.md
deploy/helm/charts/values.yaml

This PR updates the jiva-operator images to 2.10.1 version in the helm charts

chore(charts): update jiva-operator images to 2.10.1

---

.github/workflows/release.yaml

This PR addresses the issue where a release workflow is triggered when a helm chart is released. The images pushed have tags with the name of the chart like `jiva-2.1.0` in this case. We should avoid building images in such cases. The if condition added in the workflow prevents such workflows from executing.

fix(actions): skip release workflow on helm release

---

.github/workflows/build.yaml
.github/workflows/pull_request.yml
cmd/manager/main.go
deploy/hostpath-sc.yaml
pkg/controllers/jivavolume_controller.go

This PR address 2 issues:
- Rapidly cycling Unknown and Ready status:
Reason: Fetching the stats using the service IP repeatedly can cause dns issues which fails occasionally and causes cycling of status
Fix: Use controller pod IP to fetch the stats and maintain an updated map for all volumes and pod IPs 
- Log flooding of failed tcp requests
The above fix will help here as well
Tests covered manually:
- volume creation and check status
- multiple controller pod restarts 
- multiple replica pod restarts

fix(status): fetch volume status using controller podIP

---

version/util.go
version/util_test.go

This PR refactors the version validation for the jivaVolume CR during upgrades. As the versionDetails in the CR is only modified by either the upgrade job or the operator itself and is not user-facing we can switch to range-based validation. We will still maintain the upgrade matrix in upgrade repo to validate the job fields. This is eliminate the need to bump the upgrade matrix on each release.
Test case covered manually: upgraded a jiva volume from 2.9.0 to latest without any issues.

refact(version): use range instead of matrix for validation

---

version/util.go

This PR adds `master` as an exception for version checks as it is required for the ci test in the upgrade repo
Ref:  https://github.com/openebs/upgrade/pull/120/checks?check_run_id=3217599799

fix(version): add version exceptions for upgrade ci

---

e2e-tests/experiments/infra-chaos/jiva_node_failure/test.yml

- Included the always block to update the test status in the result crd spec.

Included the always block to update the test status in node failure testcase

---

deploy/helm/charts/Chart.yaml
deploy/helm/charts/templates/priority-class.yaml
deploy/helm/charts/values.yaml
deploy/jiva-csi.yaml

use jiva in priority class name to avoid naming clash between different storage engines.

update(yaml): update priority class name for csi driver
